services:
  db:
    image: mysql:5.7.35
    container_name: wykop-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - "3306:3306"
    environment: 
      MYSQL_DATABASE: wykop
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: wykop
      MYSQL_PASSWORD: wykop
      TZ: UTC
